name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      PORT: 3000  # Specify the port your Node.js application should run on
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
    - name: Start app
      run: npm start

>
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'your-region'

      - name: Copy to S3
        run: aws s3 cp ./path/to/your/app s3://your-s3-bucket/ --recursive

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/amazon-elastic-beanstalk-deploy@v1
        with:
          environment-name: 'your-environment-name'
          application-name: 'your-application-name'
          region: 'your-region'