name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  Build_Website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Start app
      run: npm start
    - name: Wait the app to be started
      run: sleep 10
    - name: Test 1 grep html components
      run: curl http://localhost:8080 | grep "People Registration App"
    - name: Test 2 Mocha test case 
      run: npm test


