name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      PORT: 3000  # Specify the port your Node.js application should run on
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
    - name: Start app
      run: npm start -s &
    - name: Add curl
      run: apk add curl
    - name: Wait for Application to Start
      run: sleep 10  # Adjust this wait time based on your application's startup tim
    - name: Perform Tests
      run: curl http://localhost:3000 | grep "People Registration App"

