name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  Build_Website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - name: Upload artefects
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: dist/bundle.js

  Test_Website: 
    runs-on: ubuntu-latest
    needs: Build_Website
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: Build
    - name: Install dependencies
      run: npm install
    - name: Start app
      run: npm start -s &
    - name: Wait for Application to Start
      run: sleep 10 
    - name: Perform Tests 1
      run:  curl http://localhost:8080 | grep "People Registration App"
    - name: Perform Tests 2
      run:  curl -X POST -H "Content-Type: application/json" -d '{"name": "AWS Cloud Club", "gender": "Other"}' http://localhost:8080/register
    - name: Perform Tests 3
      run: npm test


